### PR TITLE
Updated Issue Template

### PR DESCRIPTION
**Pull request by DEVLOPRR**
## Description
I've Added 2 Different Templates For GitHub Issues, One For Bug Reports, And One For Feature Requests And Updated Security Section.

## Changes proposed
- Removed `.github/ISSUE_TEMPLATE.md`
  - Had To Remove This File So That We Can Add Multiple Issue Templates.

- Added `.github/ISSUE_TEMPLATE/bug-report.md`
  - `bug-report.md` Is Template For Bug Reports.

- Added `.github/ISSUE_TEMPLATE/feature_request.md`
  - `feature_request.md` Is Template For Feature Requests.

### CODE REVIEW

**Comment by danidre14** [comment]
For consistency, you should either use dashes (-) for both, or underscores (_) for both:
Either `bug-report.md` and `feature-request.md`
Or `bug_report.md` and `feature_request.md`

Any reason why they differ?

**Comment by DEVLOPRR** [comment]
You can, tho i didn't touch the filenames, it is same as what github generated for me.

**Comment by pathange-s** [comment]
Are the changes directly committed to main ? I suggest checking out a new branch before any file changes on main.

**Review by shalithasuranga — APPROVED** [review]
Thanks for the contribution :+1: Please note that I've edited some stuff before merging ;)

**Pull request merged**
