### PR TITLE
added more functionality to Neutralino.window

### PR DESCRIPTION
**Pull request by AOSXAP**
## Description
A lot of users want more window functionality such as maximize , inconify and others. I managed to implement 6 functions (see below) . Tested them on Linux Ubuntu and worked flawlessly.

## Changes proposed
Neutralino.window.__navigate(url) - navigates to the given url
Neutralino.window.maximize()  ,
Neutralino.window.unmaximize()
Neutralino.window.iconify(),
Neutralino.window.deiconify(),
Neutralino.window.destroy()

## How to test it
You can easily test them in the bin folder , using the sample app there.

### CODE REVIEW

**Comment by spiderbytes** [comment]
Very nice! 

`Neutralino.window.minimize()` and `Neutralino.window.center()` would also be great! 🌻

Greetings ... Peter

**Comment by AOSXAP** [comment]
> Very nice! 
> 
> `Neutralino.window.minimize()` and `Neutralino.window.center()` would also be great! 🌻
> 
> Greetings ... Peter
> 
> 

Thanks :) . I'm not sure what you mean by minimize (i think it's what is called iconify) . If this pull request is accepted , i ll refactor a bit the code and add center too.

**Comment by alixsep** [comment]
@AOSXAP  is there a way i can contact you? may want to ask you a few stuff!

**Comment by AOSXAP** [comment]
> @AOSXAP  is there a way i can contact you? may want to ask you a few stuff!

AP#9279 on Discord

**Comment by shalithasuranga** [comment]
@AOSXAP Thanks for submitting a PR that matches our [roadmap](https://github.com/neutralinojs/proposals). I will check this and release it (for other platforms also) with [v2.5.0](https://github.com/neutralinojs/neutralinojs/milestone/17).

Please note that we will release [v2.4.1](https://github.com/neutralinojs/neutralinojs/milestone/16) (there are some bug fixes) first. Therefore, I will check and merge this in few days 👍

**Review by shalithasuranga — APPROVED** [review]
Thanks, I would like do a few adjustments to this. I will let you know here once I add them. Now I will merge this one :)

**Comment by shalithasuranga** [comment]
I did some [modifications](https://github.com/neutralinojs/neutralinojs/commit/f72384d5248242f4ec18b308fcd5b2f63f0ae9d7)
Thanks for the PR @AOSXAP :+1:

**Pull request merged**
