### PR TITLE
asio standalone

### PR DESCRIPTION
**Pull request by orent**
* Add the standalone version of asio
* Remove dependency on bloa^H^H^Hoost

### CODE REVIEW

**Comment by shalithasuranga** [comment]
Hey.. thank you very much. This is a great improvement to the codebase I think - we had to add boost just because of the WebSocket library and we don't use any Boost libs. I will test this and merge this soon :)

**Comment by shalithasuranga** [comment]
Hey.. @orent Looks like no compilation issues on Linux and macOS. But, looks like the Windows build got some troubles. Could you please check when you have some time? You can access Windows build logs here: https://github.com/neutralinojs/neutralinojs/runs/4656832110?check_suite_focus=true

**Comment by orent** [comment]
👍

**Comment by shalithasuranga** [comment]
Thanks @orent This is a great contribution.. Hey ..@corbane now what we planned earlier was done by @orent :tada: 

@orent Is it okay if we add your GitHub profile link to https://neutralino.js.org/docs/contributing/committers ? we usually update that list with contributors who've done remarkable contributions

**Comment by orent** [comment]
Sure.

**Comment by corbane** [comment]
Excellent!
Thanks @orent this helps guys like me who aren't really developers build Neu !!

**Pull request merged**
