### PR TITLE
subclassed NSWindow to fix borderless window issues and set webview to not draw background

### PR DESCRIPTION
**Pull request by monsterkodi**
## Description
fixes a bunch of issues with borderless windows on mac

## Changes proposed
 - created a subclass of NSWindow in `macwin.mm` that ...
     - sets itself to have a transparent background
     - overrides `canBecomeKeyWindow` and `canBecomeMainWindow` to always return YES
 - set key "drawsBackground" to false on `WKWebView` to enable arbitrary window shapes via document styles

### CODE REVIEW

**Comment by monsterkodi** [comment]
mhh, strange. i ran the tests on windows and didn't get the error that the build actions get.

**Comment by shalithasuranga** [comment]
Hello @monsterkodi. We can ignore that failing test on Windows (looks like there is another issue since it even happens with previous commits). I'll merge this soon after testing on Mac OS. Thanks :tada:

**Comment by monsterkodi** [comment]
oops, i messed this up :(
i intended to have the last three commits in a seperate branch and make different pull requests for them later.
i actually don't know how to solve this right now, my git knowledge isn't that fresh right now.
the problem is that i completely removed the easylogging dependency inbetween my other changes.
let me see if i can undo/seperate this again somehow.
sorry for the complications.

**Comment by monsterkodi** [comment]
uff, i think i got it reverted. 
my mess up seems to be still in the git commit history, but so be it :)

**Review by shalithasuranga — APPROVED** [review]
Hi @monsterkodi, thanks so much for your contribution. I'll add this CSS style to other templates (The default `neu create` template is on [another repo](https://github.com/neutralinojs/neutralinojs-minimal/blob/main/resources/styles.css)).

Btw. would you like to add your GitHub profile link to [Neutralinojs committers list](https://neutralino.js.org/docs/contributing/committers). We often update this list with contributors who did great contributions :tada: 

Thanks :tada:

**Comment by monsterkodi** [comment]
Hello Shalitha,

thank you for the merge. 

Yes, it would be nice to be included in that list.

A short side node: 
if you replace `c++` with `zig c++` in your bz.py you get great compile speed improvements in the development cycle.
obviously you need to have zig installed for that though :)

**Comment by shalithasuranga** [comment]
Hello @monsterkodi, Welcome, thanks for your reply. Your suggestion regarding Zig c++ toolchain looks great. I will check more about using it :tada: Thanks :)

**Pull request merged**
