### PR TITLE
Add multithreaded process spawning API

### PR DESCRIPTION
**Pull request by shalithasuranga**

### CODE REVIEW

**Comment by pathange-s** [comment]
Please do consider giving descriptions for PRs. I usually keep myself updated by reading the descriptions of PRs that get merged. That's the best way afaik, to understand what progress has been made.

**Comment by shalithasuranga** [comment]
Hey @pathange-s  nice idea :rocket: , you can check the summary in the changelog: https://github.com/neutralinojs/neutralinojs/blob/main/CHANGELOG.md#api-process-spawning-api

**Comment by pathange-s** [comment]
Cool! So, CHANGELOG.md gets updated everytime a pull request gets merged ? Is it generated automatically? or you updated it.

**Comment by pegvin** [comment]
For CHANGELOG.md he does it manually as far as i know and for GitHub release it's done automatically by [ReleaseZri](https://github.com/codezri/releasezri)

**Comment by pathange-s** [comment]
Anyways, for an ongoing pull request, there would be no proper description and will make it hard for reviewers. We can anyways update the description and later update CHANGELOG.md when the pr gets a merge.

**Pull request merged**
