### PR TITLE
Fixing bug of Minimized app display & window.show()  

### PR DESCRIPTION
**Pull request by moataz2002**
### Description:
This pull request aims to fix an issue where the application window wouldn't properly come to the foreground on Windows systems after being minimized. The previous implementation lacked proper handling to ensure the window regained focus reliably, especially on newer versions of Windows.

#### Related issues:
solved --> https://github.com/neutralinojs/neutralinojs/issues/1232 

#### Modifications:
- **Refined Window Show Logic**: Updated the `show()` function to include additional checks and actions specifically tailored for Windows platforms.
  - Restores the window if it was minimized before attempting to bring it to the foreground.
  - Utilizes `SetWindowPos` to adjust the window z-order, ensuring it's visible to the user.
  - Attempts to bring the window to the foreground using `SetForegroundWindow`.
  - Introduces a user-friendly notification mechanism, such as flashing the taskbar icon, if direct focus request fails.

#### Concerns:
- **Cross-Version Compatibility**: While these changes have been thoroughly tested on Windows 10 and Windows 11 to ensure compatibility, there might be variations in behavior across different versions or configurations of Windows. Further testing is recommended to validate the modifications in diverse environments.
- **User Experience Impact**: The introduction of a flashing taskbar icon as a notification mechanism might affect user experience, especially for users with sensitivity to visual distractions or accessibility concerns. Consider gathering user feedback or conducting usability testing to assess the impact on various user groups.
- **Fallback Mechanism**: While the flashing taskbar icon provides a user-friendly notification, it relies on user action to bring the window to the forefront. Ensure that users are adequately informed about the action required to interact with the application window if the automatic focus attempt fails.

#### Additional Notes:
- These modifications adhere to Microsoft's recommendations for managing application windows and strive to provide a seamless user experience across different Windows environments.
- Developers are encouraged to monitor user feedback and observe real-world usage patterns to iteratively refine the window focus handling based on user needs and preferences.

### Testing:
- Manual tests have been conducted on Windows 10 and Windows 11 to verify the effectiveness of the modifications in restoring application window focus.
- Automated tests have been updated to cover the new logic introduced in the `show()` function.

### Request for Comments:
Feedback is welcome on the proposed approach, especially regarding its impact on user experience and potential cross-version compatibility concerns. Additionally, suggestions for further refinement or alternative approaches are appreciated.

---

### CODE REVIEW

**Review by zoroxide — APPROVED** [review]
Fixed

**Review by shalithasuranga — CHANGES_REQUESTED** [review]
Thanks so much for this pull request @moataz2002. Could you please submit only the changes in the `window.cpp` file by using the original version of `os.cpp`. Then, we can merge this, the idea of flashing the window looks awesome :tada:

**Review by shalithasuranga — APPROVED** [review]
I've already doen required changes and this is now merged. Thanks :tada: @moataz2002

**Comment by jouni-kantola** [comment]
In Windows 11 I can't get the fix to work. I've created a new repro that is using `nightly`. Can you please test it out?
[neutralinojs-show-minimized-bug-repro.zip](https://github.com/neutralinojs/neutralinojs/files/14914818/neutralinojs-show-minimized-bug-repro.zip)

Instructions:
1. Download and unzip
2. Run `npm run update`
3. Run `npm start`
4. Click the _Show_ button. Nothing happens, I can't see the mentioned flash.
5. Click the _Minimize_ button
7. Click _Show_ in the tray menu
8. Stays minimized

Is there something I'm missing?

**Pull request merged**
