### PR TITLE
MacOS support

### LINKED ISSUE #18: MacOS Support
[Issuehunt badges](https://issuehunt.io/r/neutralinojs/neutralinojs/issues/18)

Idea proposed by Reddit user 
Check the source [here](https://www.reddit.com/r/javascript/comments/907hym/why_we_built_neutralinojs_framework_medium/e2ofukh)

## TODO

- Write neutralino server implementation(We try the existing linux and do some modifications if needed) for MacOS in `core-macos`
- Executable will be placed in to `dist/neutralino.{extension}`

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $200.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($200.00)
### Submitted pull Requests
- [#170 MacOS support](https://issuehunt.io/r/neutralinojs/neutralinojs/pull/170)
- [#173 MacOSX Support](https://issuehunt.io/r/neutralinojs/neutralinojs/pull/173)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/neutralinojs/neutralinojs/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by SirWindfield**
This PR adds support for MacOS.

It does support all `core` functionality as of now. There is a reason why I didn't implement all the other functionality. The more I worked with the protocol, the more I started to kind of dislike it. There are a lot of similarities between endpoints but their JSON POST fields have different names for example (`dir` and `path` is just an example).

I think that a complete overall and a new major version alongside improvements on this code would really benefit the project in many ways.

I still would say that you could add the code to the repository, but see it as more of a 90% done implementation for MacOS. I would be happy to work with you on the protocol first before finishing a complete implementation.

It seems that `core` is enough for most use cases. The project is pretty early on in its development cycle and I think that having a working `window` mode is a great start for MacOS support. I can add `cloud` and `browser` support later on though... As privileges and pinging as well as auth is tied to those use cases, this PR should be able to cover desktop usage completely (I.e. window mode).
This will allow us to fix any `core`-related bugs first before introducing new features :smile:
If you want to elaborate on what exactly `cloud` and `browser` do as well as how they relate to the other API calls, I will add them to the PR as well.

**Edit:** A current limitation is the fact that the `index.html` file has to be inlined. I couldn't really work around this for now. But we can tackle this one down if you want too! I used [inline-assets](https://www.npmjs.com/package/inline-assets) to generate the inlined file.

The code base works for all three major OS. This would overall improve maintainability! To try it out, install Rust following the instructions found on https://rustup.rs/.

Closes #18 .

**Edit**: I am currently in the process of analyzing multiple Electron based applications to figure out what the most called methods from NodeJS are. This would give us a good base on what functions to offer over the API.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#18: MacOS Support ](https://issuehunt.io/repos/138368259/issues/18)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by SirWindfield** [comment]
I squashed my commits to make the history a little bit cleaner, functionality didn't change.

**Comment by shalithasuranga** [comment]
@SirWindfield  We really appreciate your work whereas I had to accept the other PR by @kasvith  which is implemented using c++ because at the moment we don't want to use another programming language just only for one platform. But there is an idea to rewrite neutralino codebase into one (without having core-linux, core-macos etc). Then we would like consider this implementation  in future.

Happy coding :+1:

**Comment by SirWindfield** [comment]
Fair enough. 

Don't take this as an offense though but I don't think that maintaining three code bases is a smart idea at all. It hinders people adding new features via PRs and slows the overall project speed down.

**Comment by kasvith** [comment]
Actually we wont have to maintain 3 code bases, but definitely we would have to write platform specific codes(in seperate files)

Using a proper build system can make this process lot easier. This happens in all other platforms like V8, Chrome, Any Game Engine etc. 

I've taken initial steps towards migration, in future we would have a more clean small C++ codebase

(Don't be discouraged)

**Pull request closed without merging**
