### PR TITLE
Fix popup issue in windows when hidden set to true.

### PR DESCRIPTION
**Pull request by kodaloid**
## Description
On Windows if you launch Neutralino with `hidden: true` in the config. A window appears for a split second before disappearing. Quite a few people have expressed a wish to have this changed so that the window never appears with this setting, so this pull request introduces a solution that should work given the conditions.

I tested a lot of solutions before hand. Ideally using SW_HIDE when the window is first created would be the solution, however if you do that, the WebView component always fails to load, with a corrupt connection to it's developer tools.

## Changes proposed
The changes made in this pull request are all scoped specifically for Windows using `#if defined(_WIN32)` when needed:

- Set the X coordinate to a crazy high number when CreateWindow is called.
- Change the ex window style to WS_EX_TOOLWINDOW so that no icon appears in the taskbar.
- Provide two helper methods called `window::isFakeHidden()` and  `window::undoFakeHidden()`.

If the window didn't need to hide, or show() is called, the helper methods above provide a way to show the window again to the user.

## How to test it
Build and use the new binary, everything should work as normal, however when you set hidden to true, there will no longer be a window flashing before it hides.

### CODE REVIEW

**Comment by pegvin** [comment]
Fix for #930

**Comment by pegvin** [comment]
@shalithasuranga this pr was a bug fix, please review it.

**Comment by shalithasuranga** [comment]
Hey.. all, @kodaloid, thanks for sending this, I was planning to merge this pull request before this month's release but it looks like there is something to check further in the webview library. Let's add this solution as the first task after the release :tada: Thanks

**Comment by kodaloid** [comment]
> Hey.. all, @kodaloid, thanks for sending this, I was planning to merge this pull request before this month's release but it looks like there is something to check further in the webview library. Let's add this solution as the first task after the release 🎉 Thanks

No problem, will take a browse through the other issues to see if there's anything else I can contribute too.

**Comment by danidre14** [comment]
Any update on when this will be merged?

**Comment by kodaloid** [comment]
I imagine this may need tweaking as the most recent version of Neutralino has changed a few things. Have we found an alternative solution to the issue? If not, I'll book some time in to rework the pull request to see if we can move forward with this.

Koda

**Comment by kodaloid** [comment]
Closing this so that I can rework the patch to fit the latest release.

**Pull request closed without merging**
