### PR TITLE
Macos automated build using shell script

### LINKED ISSUE #215: Add .sh file to mac version to automate njs build same as other platforms

### PR DESCRIPTION
**Pull request by momozor**
## Description
add shell script to build core-macos and njs for macos build. Fixes #215 

## Changes proposed

 - as stated in the description above

## How to test it

 - This uses the original build.sh in the root directory. Just type bash build.sh linux to build linux build or bash build.sh macos to build macos version

## Next steps

None.

## Deploy notes

Only macos debug build is supported for this PR

### CODE REVIEW

**Comment by shalithasuranga** [comment]
@momozor  Would you like to display your name under committer list of neutralinojs ?
If you could you let us know a preferred name to be displayed in https://neutralino.js.org/docs/#/other/committers

**Comment by momozor** [comment]
@shalithasuranga Oh thanks for the offer. Sure.

**Comment by shalithasuranga** [comment]
ah sure.. looks nice . here you go https://neutralino.js.org/docs/#/other/committers

**Comment by momozor** [comment]
thanks

**Pull request merged**
