### PR TITLE
GSoC2024: TestSuite - version 5.3.0

### PR DESCRIPTION
**Pull request by Sadaf-A**
## Description
This PR adds test cases for the new version changes

## Changes proposed
- filesystem.createDirectory()
- [x] works with special characters
- filesystem.getRelativePath()
- [x] returns an error if the path field is missing
- [x] calculates relative path with a custom base path
- [x] handles paths that are equal to the base path
- filesystem.getPathParts()
- [x] returns path parts for a valid file path with no extension
- [x] returns path parts for a file path with a single dot extension
- [x] returns path parts for a path with special characters
- [x] returns path parts for a root path
- [x] returns path parts for a path with a root directory
- [x] returns path parts for a path with multiple nested directories
- [x] returns path parts for a path with a filename that starts with a dot
- [x] returns path parts for a path with absolute path separators
- os.getEnv()
- [x] retrieves value with special characters
- os.getPath()
- [x] returns a valid path

## How to test it

 - Run `cd spec && rpm test filesystem`
 - Run `cd spec && rpm test os`

### CODE REVIEW

**Review by shalithasuranga — CHANGES_REQUESTED** [review]
Hello @Sadaf-A, thanks so much for sending this PR. Could you please check why several tests are failing on Windows? Thanks :tada:

**Comment by Sadaf-A** [comment]
> Hello @Sadaf-A, thanks so much for sending this PR. Could you please check why several tests are failing on Windows? Thanks :tada:

Hey, sure I'll try to fix them now

**Comment by Sadaf-A** [comment]
Hey, could you please have a look now?

**Review by shalithasuranga — APPROVED** [review]
Looks great now. Thanks @Sadaf-A :tada:

**Pull request merged**
